-- Disable RLS for all tables
ALTER TABLE nomenclador_instrumentadores DISABLE ROW LEVEL SECURITY;
ALTER TABLE nomenclador_versiones DISABLE ROW LEVEL SECURITY;
ALTER TABLE procedimientos DISABLE ROW LEVEL SECURITY;
ALTER TABLE valores_nomenclador DISABLE ROW LEVEL SECURITY;
ALTER TABLE liquidaciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE faltantes_liquidacion DISABLE ROW LEVEL SECURITY;
ALTER TABLE instrumentadores DISABLE ROW LEVEL SECURITY;
